const express = require('express');
const banksController = require('../controller/banksController');

const router = express.Router();

router.get('/all-banks', banksController.getBanks);

router.get('/:id/branches', banksController.getBranches);

// router.post('/bank_transfer', banksController.bank_trf);

router.post('/charge_ng_account', banksController.charge_ng_acct);

router.post('/bank_holder_details', banksController.verifyAcct);

router.post('/ussd', banksController.ussd);

router.post('/send_to_account', banksController.initTrans);

router.post('/transfer_fee', banksController.getFee);

router.post('/create_otp', banksController.createOTP);

router.post('/validate_otp/:reference', banksController.validateOTP);

router.get('/verify_transactions/:id', banksController.verifyTransactions);

/**
 * @swagger
 * components:
 *    schemas:
 *      Transaction:
 *        type: object
 *        required:
 *          -amount
 *          -currency
 *          -account_bank
 *          -account_number
 *          -narration
 *          -tx_ref
 *          -reference
 *          -debit_currency
 *          -phone_number
 *          -email
 *          -fullname
 *          -country
 *          -customer
 *          -id
 *          -fee
 *          -status
 *          -bank_name
 *          -bank_code
 *        properties:
 *           amount:
 *              type: Number
 *              description: The amount of the transaction
 *           currency:
 *              type: String
 *              description: The currency in which the transaction is done. Default is NGN
 *           account_bank:
 *              type: String
 *              description: This is the bank where the customer holds an account
 *           account_number:
 *              type: String
 *              description: This is the account number of the customer
 *           narration:
 *              type: String
 *              description: The narration of the transaction
 *           tx_ref:
 *              type: String
 *              description: The autogenerated reference of the transaction
 *           reference:
 *              type: String
 *              description: The autogenerated reference of the transaction
 *           debit_currency:
 *              type: String
 *              description: The currency in which the customer is debited. Default is NGN
 *           phone_number:
 *              type: Number
 *              description: The phone number of the customer
 *           email:
 *              type: String
 *              description: The email address of the customer
 *           country:
 *              type: String
 *              description: The country. Default is NG
 *           customer:
 *              type: String
 *              description: This details of a customer
 *           account:
 *              type: String
 *              description: This details of a customer's account
 *           id:
 *              type: String
 *              description: Autogenerated id from flutterwave
 *           fee:
 *              type: Number
 *              description: The fee of a transaction
 *           status:
 *              type: String
 *              description: The status of a transaction. Pending or failed or success
 *           bank_name:
 *              type: String
 *              description: The name of the customer's bank
 *           bank_code:
 *              type: String
 *              description: The unique flutterwave bank code for Nigerian bank
 *        example:
 *          amount: 1000
 *          currency: NGN
 *          account_bank: Access Bank(044)
 *          account_number: 0690000037
 *          narration: Salary for December
 *          tx_ref: Wynk-64563783
 *          reference: Wynk-64563783
 *          debit_currency: NGN
 *          email: max@example.com
 *          phone_number: 08090000000
 *          country: NG
 *          customer: Yemi Danjuma
 *          account: 0690000037 Access Bank(044) Yemi Danjuma
 *          id: 4563738
 *          fee: 10.75NGN
 *          status: success
 *          bank_name: Access Bank(044)
 *          bank_code: 044
 *
 */

/**
 * @swagger
 * tags:
 *    name: FlutterWave
 *    description: The Wynk Flutterwave Transactions Managing API
 */

/**
 * @swagger
 * /banks/all-banks:
 *    get:
 *      summary: Get All Banks in Nigeria. Pass in country code 'NG' in query field.
 *      tags: [FlutterWave]
 *      parameters:
 *      - in: query
 *        name: country
 *        schema:
 *        type: string
 *        required: true
 *        description: This returns the list of all banks in Nigeria
 *      responses:
 *        200:
 *          description: Banks fetched successfully
 *          content:
 *             application/json:
 *                 schema:
 *                 type: String
 *                 example:
 *                     id: 1
 *                     code: '044'
 *                     name: Access Bank
 *        500:
 *          description: Internal Server error
 */

/**
 * @swagger
 * /banks/charge_ng_account:
 *    post:
 *      summary: Charge a customer's NUBAN
 *      tags: [FlutterWave]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *              schema:
 *                 $ref: '#/components/schemas/Transaction'
 *              example:
 *                  amount: 1000
 *                  account_bank: '044'
 *                  account_number: '0690000037'
 *                  email: max@example.com
 *                  phoneNumber: '09012345678'
 *                  fullName: Yemi Danjuma
 *      responses:
 *          201:
 *            description: Charge successful
 *            content:
 *                application/json:
 *                    schema:
 *                       $ref: '#/components/schemas/Transaction'
 *                    example:
 *                        id: 4099423
 *                        tx_ref: wynk-11806651
 *                        amount: 10000
 *                        currency: NGN
 *                        narration: Wynk Limited
 *                        status: successful
 *                        customer: Yemi Danjuma
 *                        account: '0690000037'
 *                        meta: Please dial *901*4*1# to get your OTP. Enter the OTP gotten in the field below
 *          400:
 *            description: Transaction Failed
 *
 *          500:
 *            description: Internal server error. Try again
 */

module.exports = router;
