const express = require('express');
const billsController = require('../controller/billPaymemtsController');

const router = express.Router();

router.post('/create-bill', billsController.createBill);

router.get('/bill-categories', billsController.getBillsCategories);

router.get('/bill_payment_status/:refId', billsController.getStatus);

router.post('/validate_bill', billsController.validateBill);

router.get('/bills-payment', billsController.getBillsPayment);

/**
 * @swagger
 * components:
 *    schemas:
 *      Bill:
 *        type: object
 *        required:
 *          -amount
 *          -currency
 *          -narration
 *          -tx_ref
 *          -reference
 *          -email
 *          -fullname
 *          -country
 *          -customerID
 *          -id
 *        properties:
 *           amount:
 *              type: Number
 *              description: The amount of the transaction
 *           currency:
 *              type: String
 *              description: The currency in which the transaction is done. Default is NGN
 *           tx_ref:
 *              type: String
 *              description: The autogenerated reference of the transaction
 *           reference:
 *              type: String
 *              description: The autogenerated reference of the transaction
 *           country:
 *              type: String
 *              description: The country. Default is NG
 *           customerID:
 *              type: String
 *              description: This details of a customer
 *           status:
 *              type: String
 *              description: The status of a transaction. Pending or failed or success
 *           id:
 *              type: String
 *              description: The unique Flutterwave id generated when a bill is created
 *        example:
 *          amount: 1000
 *          tx_ref: Wynk-64563783
 *          reference: Wynk-64563783
 *          type: AIRTIME
 *          customerID: 08090000000
 *          country: NG
 */

/**
 * @swagger
 * tags:
 *    name: Bills
 *    description: The Wynk Flutterwave Bill Payments Managing API
 */

/**
 * @swagger
 * /bills/create-bill:
 *    post:
 *      summary: Buy airtime, data bundles, pay for GOTV & DSTV
 *      tags: [Bills]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *              schema:
 *                 $ref: '#/components/schemas/Bill'
 *              example:
 *                  customerID: 08090000000
 *                  amount: 100
 *                  type: AIRTIME
 *      responses:
 *          200:
 *            description: Bill payment successful
 *            content:
 *                application/json:
 *                    schema:
 *                       $ref: '#/components/schemas/Bill'
 *                    example:
 *                        phone_number: +23490803840303
 *                        tx_ref: BPUSSD1583957963415840
 *                        flw_ref: CF-FLYAPI-20200311081921359990
 *                        amount: 100
 *                        network: MTN
 *                        reference: wynk-355476
 *          400:
 *            description: Transaction Failed. Insufficient funds in your wallet
 *
 *          500:
 *            description: Internal server error. Try again
 */

/**
 * @swagger
 * /bills/bill-categories:
 *    get:
 *      summary: Get All Bill Categories.
 *      tags: [Bills]
 *      responses:
 *        200:
 *          description: Bills fetched successfully
 *          content:
 *             application/json:
 *                 schema:
 *                 type: String
 *                 examples:
 *                    CableTv:
 *                      value:
 *                         name: DSTV Premium
 *                         amount: 14600
 *                         item_code: CB137
 *                         biller_code: BIL120
 *                    DataBundle:
 *                      value:
 *                         name: MTN 3.5 GB
 *                         amount: 2000
 *                    Airtime:
 *                      value:
 *                         name: MTN VTU
 *                         amount: 1000
 *        500:
 *          description: Internal Server error
 */

/**
 * @swagger
 * /bills/bill_payment_status/{refId}:
 *    get:
 *      summary: Get the status of a Bill Payment
 *      tags: [Bills]
 *      parameters:
 *      - in: path
 *        name: tx_ref
 *        schema:
 *        type: string
 *        required: true
 *        description: This is the tx_ref of the bill transaction
 *      responses:
 *        200:
 *          description: Bill status fetch successful
 *          content:
 *             application/json:
 *                 schema:
 *                 type: String
 *                 example:
 *                     tx_ref: CF-FLYAPI-201808240106311799470372
 *                     amount: 500
 *                     fee: "0"
 *                     currency: NGN
 *                     flw_ref: CF-FLYAPI-201808240106311799470372
 *        404:
 *          description: Transaction not found
 *          content:
 *             application/json:
 *                 schema:
 *                 type: String
 *                 example:
 *                     status: error
 *                     message: Transaction not found
 *                     data: null
 */

/**
 * @swagger
 * /bills/validate_bill:
 *    post:
 *      summary: This is either to validate phone number, DSTV or GOTV IUC number, electric meter No.
 *      tags: [Bills]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *              schema:
 *                 $ref: '#/components/schemas/Bill'
 *              example:
 *                  item_code: CB483
 *                  biller_code: BIL121
 *                  customerID: 1059377495
 *      responses:
 *          200:
 *            description: Item validated successfully
 *            content:
 *                application/json:
 *                    schema:
 *                       $ref: '#/components/schemas/Bill'
 *                    example:
 *                        name: Stan Dele SEII POYEN
 *                        biller_code: BIL121
 *                        product_code: CB483
 *                        customer: 1059377495
 *          400:
 *            description: Biller Item could not be found
 *
 *          500:
 *            description: Internal server error. Try again
 */

module.exports = router;
