const express = require('express');
const cardsController = require('../controller/cardsController');

const router = express.Router();

router.post('/charge_card', cardsController.chargeCard);

router.post('/charge_card/validate/:flw_ref', cardsController.validateCard);

/**
 * @swagger
 * components:
 *    schemas:
 *      Card:
 *        type: object
 *        required:
 *          -card_number
 *          -card_number
 *          -expiry_month
 *          -expiry_year
 *          -currency
 *          -amount
 *          -fullname
 *          -email
 *          -phone_number
 *        properties:
 *           card_number:
 *              type: Number
 *              description: The customer card number
 *           cvv:
 *              type: Number
 *              description: The card CVV
 *           expiry_month:
 *              type: String
 *              description: Card expiry month
 *           expiry_year:
 *              type: Number
 *              description: Card expiry year
 *           currency:
 *              type: String
 *              description: The currency. Default is NGN
 *           amount:
 *              type: Number
 *              description: This details of a customer
 *           fullname:
 *              type: String
 *              description: The customer fullname
 *           email:
 *              type: String
 *              description: The customer email
 *           phone_number:
 *              type: String
 *              description: The customer phone number
 *        example:
 *          card_number: '5531886652142950'
 *          cvv: '564'
 *          expiry_month: '09'
 *          expiry_year: 32
 *          currency: 'NGN'
 *          amount: 100
 *          fullname: Yemi Demola
 *          email: max@example.com
 *          phone_number: '09000000000'
 */

/**
 * @swagger
 * tags:
 *    name: Cards
 *    description: The Wynk Flutterwave Card Payments Managing API
 */

/**
 * @swagger
 * /cards/charge_card:
 *    post:
 *      summary: Charge a customer's card
 *      tags: [Cards]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *              schema:
 *                 $ref: '#/components/schemas/Card'
 *              example:
 *                  card_number: '5531886652142950'
 *                  cvv: '564'
 *                  expiry_month: '09'
 *                  expiry_year: '32'
 *                  amount: '1000'
 *                  fullname: Yemi Danjuma
 *                  email: max@example.com
 *                  phone_number: '09012345678'
 *      responses:
 *          200:
 *            description: Charge initiated
 *            content:
 *                application/json:
 *                    schema:
 *                       $ref: '#/components/schemas/Card'
 *                    example:
 *                        id: 4099423
 *                        tx_ref: FLW-MOCK-da7d8dfce296498176ef0c4a7e9c73ca
 *                        amount: 10000
 *                        currency: NGN
 *                        narration: CARD Transaction
 *                        status: pending
 *                        customer: Yemi Danjuma
 *                        processor_response: Please enter the OTP sent to your mobile number 080****** and email te**@rave**.com
 *          400:
 *            description: Transaction Failed
 *
 *          500:
 *            description: Internal server error. Try again
 */

/**
 * @swagger
 * /cards/charge_card/validate/{flw_ref}:
 *    post:
 *      summary: Validate Card Transfer
 *      tags: [Cards]
 *      parameters:
 *      - in: path
 *        name: flw_ref
 *        schema:
 *        type: string
 *        required: true
 *        description: Unique reference generated by Flutterwave after charge is initiated
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *              schema:
 *                 $ref: '#/components/schemas/Card'
 *              example:
 *                  otp: '12345'
 *      responses:
 *          200:
 *            description: Charge validated
 *            content:
 *                application/json:
 *                    schema:
 *                       $ref: '#/components/schemas/Card'
 *                    example:
 *                        id: 4099423
 *                        tx_ref: FLW-MOCK-da7d8dfce296498176ef0c4a7e9c73ca
 *                        amount: 10000
 *                        currency: NGN
 *                        narration: CARD Transaction
 *                        status: successful
 *                        customer: Yemi Danjuma
 *          400:
 *            description: Invalid transaction attempt. No REF Cache
 *
 *          500:
 *            description: Internal server error. Try again
 */

module.exports = router;
